# Generated by Django 2.0.2 on 2018-02-26 12:01

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0012_auto_20180219_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceData',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
            },
            bases=('config.device',),
        ),
    ]
