# Generated by Django 2.0.2 on 2018-02-23 11:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0012_auto_20180219_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceDynamicData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('data', jsonfield.fields.JSONField(default=dict, help_text='dynamic device data in NetJSON DeviceMonitoring format', verbose_name='data')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_data', to='config.Device')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
