# Generated by Django 4.0.4 on 2022-06-03 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_monitoring', '0006_alter_wificlient_field_ht_vht'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wificlient',
            options={'ordering': ('-created',), 'verbose_name': 'WiFi Client'},
        ),
    ]
