# Generated by Django 5.2.6 on 2025-10-22 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("device_monitoring", "0009_update_device_status_for_disabled_critical_checks"),
        ("geo", "0003_alter_devicelocation_floorplan_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Map",
            fields=[],
            options={
                "abstract": False,
                "proxy": True,
                "swappable": "DEVICE_MONITORING_MAP_MODEL",
                "indexes": [],
                "constraints": [],
            },
            bases=("geo.location",),
        ),
    ]
