# Generated by Django 4.2.20 on 2025-06-10 20:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("geo", "0003_alter_devicelocation_floorplan_location"),
        ("device_monitoring", "0009_update_device_status_for_disabled_critical_checks"),
    ]

    operations = [
        migrations.CreateModel(
            name="Map",
            fields=[],
            options={
                "abstract": False,
                "proxy": True,
                "swappable": "DEVICE_MONITORING_MAP_MODEL",
                "indexes": [],
                "constraints": [],
            },
            bases=("geo.location",),
        ),
    ]
