# Generated by Django 3.0.4 on 2020-04-21 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_data_migration'),
    ]

    operations = [
        migrations.RemoveField(model_name='notificationuser', name='user',),
        migrations.DeleteModel(name='Notification',),
        migrations.DeleteModel(name='NotificationUser',),
    ]
