#!/bin/bash
set -e
openwisp-utils-qa-checks \
  --migration-path "./openwisp_monitoring/check/migrations \
                    ./openwisp_monitoring/device/migrations \
                    ./openwisp_monitoring/monitoring/migrations \
                    ./openwisp_monitoring/notifications/migrations" \
  --migration-module "check device_monitoring monitoring notifications"
