# Generated by Django 3.0.3 on 2020-05-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('sample_check', '0001_initial')]

    operations = [
        migrations.AddField(
            model_name='check',
            name='last_called',
            field=models.DateTimeField(blank=True, null=True),
        )
    ]
