# Generated by Django 3.0.3 on 2020-05-20 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_check', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(name='DetailsModel',),
    ]
