# Generated by Django 5.2.4 on 2025-07-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample_check", "0003_add_check_inline_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="check",
            name="params",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="parameters needed to perform the check",
                verbose_name="parameters",
            ),
        ),
    ]
