# Generated by Django 3.0.3 on 2020-05-29 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_monitoring', '0002_add_details_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='configuration',
            field=models.CharField(
                choices=[
                    ('bad_test', 'Bugged chart for testing purposes'),
                    ('default', 'Default query for testing purposes'),
                    ('disk', 'Disk Usage'),
                    ('dummy', 'Dummy chart'),
                    ('histogram', 'Histogram'),
                    ('load', 'CPU Load'),
                    ('mean_test', 'Mean test'),
                    ('memory', 'Memory'),
                    ('multiple_test', 'Multiple test'),
                    ('packet_loss', 'Packet loss'),
                    ('rtt', 'Round Trip Time'),
                    ('sum_test', 'Sum test'),
                    ('top_fields_mean', 'Top fields mean test'),
                    ('traffic', 'Traffic'),
                    ('uptime', 'Uptime'),
                    ('wifi_clients', 'WiFi clients'),
                ],
                max_length=16,
                null=True,
            ),
        ),
    ]
