# Generated by Django 4.0.4 on 2022-08-19 11:28

from django.db import migrations

from openwisp_monitoring.monitoring.migrations import (
    assign_alertsettings_inline_permissions_to_groups,
)


class Migration(migrations.Migration):

    dependencies = [
        ('sample_monitoring', '0002_create_general_metric'),
    ]

    operations = [
        migrations.RunPython(
            assign_alertsettings_inline_permissions_to_groups,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
