# Generated by Django 3.2.15 on 2022-09-08 11:11

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sample_monitoring", "0003_add_alertsettings_inline_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metric",
            name="field_name",
            field=models.CharField(
                blank=True,
                default="value",
                help_text="leave blank to determine automatically",
                max_length=16,
            ),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name="metric",
                    index=django.contrib.postgres.indexes.GinIndex(
                        fields=["main_tags"],
                        name="main_tags_gin_idx",
                    ),
                ),
                migrations.AddIndex(
                    model_name="metric",
                    index=django.contrib.postgres.indexes.GinIndex(
                        fields=["extra_tags"],
                        name="extra_tags_gin_idx",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
