# Generated by Django 5.2.4 on 2025-07-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample_monitoring", "0004_alter_metric_field_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metric",
            name="extra_tags",
            field=models.JSONField(blank=True, default=dict, verbose_name="extra tags"),
        ),
        migrations.AlterField(
            model_name="metric",
            name="main_tags",
            field=models.JSONField(
                blank=True, db_index=True, default=dict, verbose_name="main tags"
            ),
        ),
    ]
