# Generated by Django 3.2.10 on 2022-01-05 17:45

from django.db import migrations, models


def populate_is_healthy_tolerant(apps, schema_editor):
    Metric = apps.get_model('monitoring', 'Metric')
    chunk_size = 2000
    metrics = []
    for metric in (
        Metric.objects.filter(is_healthy__isnull=False)
        .only('id', 'is_healthy')
        .iterator(chunk_size=chunk_size)
    ):
        metric.is_healthy_tolerant = metric.is_healthy
        metrics.append(metric)
        if len(metrics) == chunk_size:
            Metric.objects.bulk_update(metrics, fields=['is_healthy_tolerant'])
            metrics = []
    if metrics:
        Metric.objects.bulk_update(metrics, fields=['is_healthy_tolerant'])


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_squashed_0023_alert_settings_tolerance_remove_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='is_healthy_tolerant',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.RunPython(
            populate_is_healthy_tolerant, reverse_code=migrations.RunPython.noop
        ),
    ]
