# Generated by Django 2.1.5 on 2019-02-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('monitoring', '0002_is_healthy')]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='type',
            field=models.CharField(
                choices=[('line', 'Line'), ('histogram', 'Histogram')],
                default='line',
                max_length=16,
                verbose_name='chart type',
            ),
        ),
        migrations.AddField(
            model_name='graph',
            name='top_fields',
            field=models.PositiveIntegerField(
                default=0,
                help_text='substitutes {fields} in the query with the top '
                'N fields, a value of zero disables this feature',
                verbose_name='top fields',
            ),
        ),
    ]
