# Generated by Django 2.1.8 on 2019-04-27 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('monitoring', '0003_graph_type')]

    operations = [
        migrations.RemoveField(model_name='notificationuser', name='user'),
        migrations.DeleteModel(name='NotificationUser'),
    ]
