# Generated by Django 3.0.4 on 2020-04-28 17:22

from django.db import migrations, models
from ..charts import get_chart_configuration_choices


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_metric_is_heathy_unknown'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='configuration',
            field=models.CharField(
                choices=get_chart_configuration_choices(), max_length=16, null=True
            ),
        ),
    ]
