# Generated by Django 3.0.3 on 2020-04-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_metric_is_heathy_unknown'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='query_parameters',
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name='Query Parameters'
            ),
        ),
    ]
