# Generated by Django on 2026-02-23
# Replaces third-party jsonfield.fields.JSONField with Django's built-in models.JSONField

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0012_migrate_signal_metrics"),
    ]

    operations = [
        # First change the fields to TextField so Django drops the old
        # text_pattern_ops LIKE indexes created for the previous
        # text-backed JSONField implementation.
        migrations.AlterField(
            model_name="metric",
            name="main_tags",
            field=models.TextField(
                blank=True,
                default=dict,
                verbose_name="main tags",
            ),
        ),
        migrations.AlterField(
            model_name="metric",
            name="extra_tags",
            field=models.TextField(
                blank=True,
                default=dict,
                verbose_name="extra tags",
            ),
        ),
        # Then convert to native PostgreSQL jsonb-backed JSONField.
        migrations.AlterField(
            model_name="metric",
            name="main_tags",
            field=models.JSONField(
                blank=True,
                db_index=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                verbose_name="main tags",
            ),
        ),
        migrations.AlterField(
            model_name="metric",
            name="extra_tags",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                verbose_name="extra tags",
            ),
        ),
    ]
