# Generated by Django 3.0.3 on 2020-07-10 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('monitoring', '0014_data_migration')]

    operations = [
        migrations.DeleteModel(name='Graph'),
        migrations.DeleteModel(name='Threshold'),
    ]
