# Generated by Django 3.0.3 on 2020-07-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0017_merge_traffic_metrics_and_fill_metric_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertsettings',
            name='is_active',
            field=models.BooleanField(
                default=True,
                help_text='whether alerts are enabled for this metric, uncheck to disable the alert without deleting the alert settings',
                verbose_name='Alerts enabled',
            ),
        )
    ]
