# Generated by Django 3.0.3 on 2020-08-03 10:37

from django.core.validators import MaxValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('monitoring', '0018_alertsettings_is_active')]

    operations = [
        migrations.RenameField(
            model_name='alertsettings', old_name='operator', new_name='custom_operator'
        ),
        migrations.RenameField(
            model_name='alertsettings', old_name='value', new_name='custom_threshold'
        ),
        migrations.RenameField(
            model_name='alertsettings', old_name='seconds', new_name='custom_tolerance'
        ),
        migrations.AlterField(
            model_name='alertsettings',
            name='custom_threshold',
            field=models.FloatField(
                blank=True,
                help_text='threshold value',
                null=True,
                verbose_name='threshold value',
            ),
        ),
        migrations.AlterField(
            model_name='alertsettings',
            name='custom_tolerance',
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text='for how many minutes should the threshold value be crossed before '
                'an alert is sent? A value of zero means the alert is sent immediately',
                null=True,
                validators=[MaxValueValidator(10080)],
                verbose_name='threshold tolerance',
            ),
        ),
        migrations.AlterField(
            model_name='alertsettings',
            name='custom_operator',
            field=models.CharField(
                blank=True,
                choices=[('<', 'less than'), ('>', 'greater than')],
                max_length=1,
                null=True,
                verbose_name='operator',
            ),
        ),
    ]
