# Generated by Django 3.0.3 on 2020-08-28 09:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('monitoring', '0022_delete_resources_metric_data')]

    operations = [
        migrations.AlterField(
            model_name='alertsettings',
            name='custom_tolerance',
            field=models.PositiveIntegerField(
                blank=True,
                help_text='for how many minutes should the threshold value '
                'be crossed before an alert is sent? A value of zero means '
                'the alert is sent immediately',
                null=True,
                validators=[django.core.validators.MaxValueValidator(10080)],
                verbose_name='threshold tolerance',
            ),
        )
    ]
