# Generated by Django 3.0.5 on 2020-05-27 03:06

import uuid

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import swapper
from django.db import migrations, models

import openwisp_monitoring.device.base.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [('config', '0027_add_indexes_on_ip_fields')]

    operations = [
        migrations.CreateModel(
            name='DeviceData',
            fields=[],
            options={'proxy': True, 'indexes': [], 'constraints': []},
            bases=(
                openwisp_monitoring.device.base.models.AbstractDeviceData,
                swapper.get_model_name('config', 'Device'),
            ),
        ),
        migrations.CreateModel(
            name='DeviceMonitoring',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'created',
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name='created',
                    ),
                ),
                (
                    'modified',
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name='modified',
                    ),
                ),
                (
                    'status',
                    model_utils.fields.StatusField(
                        choices=[
                            ('unknown', 'unknown'),
                            ('ok', 'ok'),
                            ('problem', 'problem'),
                            ('critical', 'critical'),
                        ],
                        db_index=True,
                        default='unknown',
                        help_text='"unknown" means the device has been recently added; \n'
                        '"ok" means the device is operating normally; \n'
                        '"problem" means the device is having issues but it\'s still reachable; \n'
                        '"critical" means the device is not reachable or in critical conditions;',
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name='health status',
                    ),
                ),
                (
                    'device',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='monitoring',
                        to=swapper.get_model_name('config', 'Device'),
                    ),
                ),
                (
                    'details',
                    models.CharField(default='devicemonitoring', max_length=64),
                ),
            ],
            options={'abstract': False},
        ),
    ]
