# Generated by Django 3.0.3 on 2020-05-20 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0003_default_group_permissions'),
        ('device_monitoring', '0002_devicemonitoring'),
        ('geo', '0002_default_groups_permissions'),
        ('config', '0026_hardware_id_not_unique'),
        ('sample_device_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(model_name='devicemonitoring', name='device',),
        migrations.DeleteModel(name='DeviceData',),
        migrations.DeleteModel(name='DeviceMonitoring',),
        migrations.CreateModel(
            name='DeviceData',
            fields=[],
            options={'proxy': True, 'indexes': [], 'constraints': [],},
            bases=('device_monitoring.devicedata',),
        ),
        migrations.CreateModel(
            name='DeviceMonitoring',
            fields=[],
            options={
                'abstract': False,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('device_monitoring.devicemonitoring',),
        ),
    ]
