# Generated by Django 4.2.17 on 2025-03-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('check', '0010_create_data_collected_check'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='check',
            index=models.Index(
                fields=['content_type', 'object_id', 'is_active'],
                name='active_object_checks_idx',
            ),
        ),
    ]
