# Generated by Django 5.2.4 on 2025-07-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("check", "0011_check_active_object_checks_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="check",
            name="params",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="parameters needed to perform the check",
                verbose_name="parameters",
            ),
        ),
    ]
