# Generated by Django on 2026-02-23
# Replaces third-party jsonfield.fields.JSONField with Django's built-in models.JSONField

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("check", "0011_check_active_object_checks_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="check",
            name="params",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text="parameters needed to perform the check",
                verbose_name="parameters",
            ),
        ),
    ]
